service:
  name: iam-checker-example

plugins:
  - serverless-webpack
  - serverless-plugin-iam-checker

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
