service:
  name: iam-checker-default

plugins:
  - serverless-webpack
  - serverless-plugin-iam-checker

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
